dashboard/urls.py
from django.urls import path
from .views import show_main, register, login_user, logout_user, profile, show_xml_by_id, show_json, show_json_by_id, show_xml, edit_journal, delete_journal, create_journal_entry_ajax, get_stores

app_name = 'dashboard'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),\
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('edit-journal/<uuid:id>', edit_journal, name='edit_journal'),
    path('delete-journal/<uuid:id>', delete_journal, name='delete_journal'),
    path('create_journal_entry_ajax', create_journal_entry_ajax, name='create_journal_entry_ajax'),
    path('get-stores/', get_stores, name='get_stores'),
]

product_page/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import product_detail, add_review, edit_review, delete_review

app_name = 'main'

urlpatterns = [
    path('product_page/', views.product_page, name='product_page'),
    path('import-csv/', views.import_csv, name='import_csv'),
    path('product_page/<uuid:product_id>/', product_detail, name='product_detail'),
    path('product_page/<uuid:product_id>/add-review/', add_review, name='add_review'),
    path('product_page/<uuid:product_id>/edit-review/<int:review_id>/', edit_review, name='edit_review'),  # Edit review
    path('product_page/<uuid:product_id>/delete-review/<int:review_id>/', delete_review, name='delete_review'),  # Delete review
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whatToEat/urls.py
from django.urls import path
from whatToEat.views import show_slider, get_products, get_detail

app_name = 'card'

urlpatterns = [
    path('', show_slider, name='WhatToEat'),
    path('get_products/', get_products, name='get_products'),
    path('product_page/<uuid:product_id>/', get_detail, name='get_detail'),
]

why_bandung/urls.py
from django.contrib import admin
from django.urls import path, include, include
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admintab/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product_page.urls')),
    path('admin/', include('dashboard_admin.urls')),
    path('whatToEat/', include('whatToEat.urls')),
    path('geomap/', include('geomapping.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
import uuid 
from django.contrib.auth.models import User
from dashboard_admin.models import ProductEntry, TokoEntry

class JournalEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    store = models.CharField(max_length=255)
    time = models.DateField(auto_now_add=True)
    description = models.TextField()
    ratings = models.DecimalField(max_digits=2, decimal_places=1)

class UserHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product = models.ForeignKey(ProductEntry, on_delete=models.CASCADE)

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from dashboard.models import JournalEntry
from dashboard_admin.models import ProductEntry, TokoEntry

class journalEntryForm(forms.ModelForm):
    store = forms.ModelChoiceField(
        queryset=TokoEntry.objects.all(),  
        widget=forms.Select(attrs={
            'class': 'appearance-none rounded-md block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'
        }),
        empty_label="Select a Store" 
    )

    class Meta:
        model = JournalEntry
        fields = ['title', 'store', 'description', 'ratings' ]

dashboard/views.py
from django.shortcuts import render
from dashboard_admin.models import ProductEntry, TokoEntry
from product_page.views import import_csv
from dashboard.models import JournalEntry
from dashboard.forms import journalEntryForm
from django.http import JsonResponse

import datetime
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render, redirect  
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required

from django.utils.html import strip_tags

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

def chunked(iterable, n):
    return [iterable[i:i + n] for i in range(0, len(iterable), n)]

def get_stores(request):
    stores = TokoEntry.objects.all().values('id', 'name')
    store_list = list(stores)
    return JsonResponse(store_list, safe=False)

def show_main(request):
    import_csv(request)

    products = ProductEntry.objects.all()
    product_chunks = chunked(products, 3)

    return render(request, "main.html", {'product_chunks': product_chunks})

@login_required(login_url='/login')
def profile(request):
    return render(request, "profile.html")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('dashboard:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("dashboard:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
       form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('dashboard:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
@require_POST
def create_journal_entry_ajax(request):
    title = strip_tags(request.POST.get("title"))
    store = strip_tags(request.POST.get("store"))
    description = strip_tags(request.POST.get("description"))
    time = strip_tags(request.POST.get("time"))
    ratings = strip_tags(request.POST.get("ratings"))
    user = request.user

    new_journal = JournalEntry(
        title=title, 
        store=store,
        description=description,
        time=time,
        ratings=ratings,
        user=user
    )
    new_journal.save()

    return HttpResponse(b"CREATED", status=201)

def edit_journal(request, id):
    journal_from_id = JournalEntry.objects.get(pk = id)
    journal_form = journalEntryForm(request.POST or None, instance=journal_from_id)

    if journal_form.is_valid() and request.method == "POST":
        journal_form.save()
        return HttpResponseRedirect(reverse('dashboard:profile'))

    context = {'form': journal_form}
    return render(request, "edit_journals.html", context)

def delete_journal(request, id):
    journal_from_id =  JournalEntry.objects.get(pk = id)
    journal_from_id.delete()

    return HttpResponseRedirect(reverse('dashboard:profile'))

def show_xml(request):
    data =  JournalEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data =  JournalEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data =  JournalEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data =  JournalEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

dashboard/templates/carousel.html
<div id="product-carousel" class="relative w-full" data-carousel="static">
    <div class="relative overflow-hidden rounded-lg md:h-96 mx-4">
        {% for product_chunk in product_chunks %}
            <div class="{% if forloop.first %}block{% else %}hidden{% endif %} duration-700 ease-in-out grid grid-cols-1 md:grid-cols-3 gap-4" data-carousel-item>
                {% for product in product_chunk %}
                    {% if product %}
                        <!-- Make the entire card clickable by wrapping all content inside <a> -->
                        <a href="{% url 'main:product_detail' product.id %}" class="block bg-gray-50 shadow-md overflow-hidden rounded-lg cursor-pointer hover:-translate-y-2 transition-all relative">
                            <div class="w-full h-[260px] p-4 overflow-hidden mx-auto aspect-w-16 aspect-h-8">
                                <img src="{{ product.image }}" alt="{{ product.name }}" class="h-full w-full object-cover" />
                            </div>
                            <div class="p-6 bg-white">
                                <h3 class="text-lg font-bold text-gray-800">{{ product.name }}</h3>
                                <h4 class="text-lg text-gray-800 font-bold mt-2">{{ product.store }}</h4>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    <!-- Slider controls -->
    <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 group-hover:bg-white/50">
            <svg class="w-6 h-6 text-gray-800" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"></path>
            </svg>
        </span>
    </button>
    
    <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 group-hover:bg-white/50">
            <svg class="w-6 h-6 text-gray-800" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7"></path>
            </svg>
        </span>
    </button>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const items = document.querySelectorAll('[data-carousel-item]');
        let currentItemIndex = 0;

        function showSlide(index) {
            items.forEach((item, i) => {
                item.classList.toggle('hidden', i !== index);
                item.classList.toggle('block', i === index);
            });
        }

        function moveToNextSlide() {
            currentItemIndex = (currentItemIndex + 1) % items.length;
            showSlide(currentItemIndex);
        }

        function moveToPreviousSlide() {
            currentItemIndex = (currentItemIndex - 1 + items.length) % items.length;
            showSlide(currentItemIndex);
        }

        // Add event listeners for next/prev buttons
        document.querySelector('[data-carousel-next]').addEventListener('click', moveToNextSlide);
        document.querySelector('[data-carousel-prev]').addEventListener('click', moveToPreviousSlide);

        // Initially show the first slide
        showSlide(currentItemIndex);
    });
</script>

dashboard/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="bg-gray-50">
    <div class="min-h-screen flex flex-col items-center justify-center px-4">
      <div class="max-w-md w-full">

        <div class="p-8 rounded-2xl bg-white shadow">
          <h2 class="text-gray-800 text-center text-2xl font-bold">Sign in</h2>
          <form class="mt-8 space-y-6 form" method="POST" action="">
            {% csrf_token %}
            <div>
              <label class="text-gray-800 text-sm mb-2 block">Username</label>
              <div class="relative flex items-center">
                <input name="username" type="text" required class="w-full text-gray-800 text-sm border border-gray-300 px-4 py-3 rounded-md outline-blue-600" placeholder="Enter Username" />
              </div>
            </div>

            <div>
              <label class="text-gray-800 text-sm mb-2 block">Password</label>
              <div class="relative flex items-center">
                <input name="password" type="password" required class="w-full text-gray-800 text-sm border border-gray-300 px-4 py-3 rounded-md outline-blue-600" placeholder="Enter Password" />
              </div>
            </div>
            
            {% if messages %}
            <div class="mt-4">
            {% for message in messages %}
            {% if message.tags == "success" %}
                    <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                        <span class="block sm:inline">{{ message }}</span>
                    </div>
                {% elif message.tags == "error" %}
                    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                        <span class="block sm:inline">{{ message }}</span>
                    </div>
                {% else %}
                    <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                        <span class="block sm:inline">{{ message }}</span>
                    </div>
                {% endif %}
            {% endfor %}
            </div>
            {% endif %}

            <div class="!mt-8">
                <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-web hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"> Sign in
                </button>
            </div>
            <p class="text-gray-800 text-sm !mt-8 text-center">Don't have an account? <a href="{% url 'dashboard:register' %}" class="text-blue-600 hover:underline ml-1 whitespace-nowrap font-semibold">Register here</a></p>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

dashboard/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>WhyBandung?</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
<div class="relative font-sans pt-32 before:absolute before:w-full before:h-full before:inset-0 before:bg-black before:opacity-50 before:z-10">
  <img src="{% static 'image/mainbanner.png' %}" alt="Banner Image" class="absolute inset-0 w-full h-full object-cover"/>

  <div class="min-h-[350px] relative z-20 h-full max-w-6xl mx-auto flex flex-col justify-center items-center text-center text-white py-6">
    <img src="{% static 'image/logo.png' %}" alt="WhyBandung Logoo" class="h-32 object-contain">
    <br>
    <h2 class="sm:text-4xl text-2xl font-bold mb-6">Find The Best Culinary Destination</h2>

    <div class="flex overflow-hidden mx-auto font-[sans-serif]">
      <form method="get" action="{% url 'main:product_page' %}" class="flex items-center max-w-sm mx-auto">   
          <label for="name" class="sr-only">Search</label>
          <div class="relative w-full">
              <input type="text" name="name" id="name" value="{{ request.GET.name }}" 
                     class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-0 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
                     placeholder="Search food name..." required />
          </div>
          <button type="submit" class="p-2.5 ms-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
              </svg>
              <span class="sr-only">Search</span>
          </button>
      </form>
    </div>
  </div>
</div>

<div class="overflow-hidden my-12">
    <h2 class="text-4xl font-extrabold text-gray-800 mt-6 mb-12 mx-auto p-4" >Traveler's Choice</h2>
    {% include 'carousel.html' %}
</div>

<div class="grid md:grid-cols-3 gap-6 min-h-[164px] py-8 p-16 font-sans overflow-hidden bg-cover bg-center" style="background-image: url('{% static "image/foodfinder.png" %}');">
  <div class="md:col-span-1 bg-red-web bg-opacity-80 p-6 rounded-lg">
    <h1 class="text-3xl font-bold text-white">A New Way to Find Delicacies</h1>
    <p class="text-base text-gray-200 mt-4">Try Our Automatic Card Recommendation</p>

    <a href="{% url 'card:WhatToEat' %}">
      <button type="button" class="py-3 px-6 text-sm font-semibold bg-white text-red-web hover:bg-slate-100 rounded-md mt-8">Try FoodFinder</button>
    </a>
  </div>
</div>


{% endblock content %}

dashboard/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>WhyBandung?</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}

<div class="flex flex-col min-h-screen bg-gray-100">
    <div class="container mx-auto px-4 py-4 mt-16">
        <div class="container-fluid">
            <div class="bg-gray-200 relative rounded flex flex-col items-center justify-center text-center py-6">
                <img src="https://www.svgrepo.com/show/355933/user-circle.svg" class="w-32 h-32 rounded-full mt-12 bg-gray-200" />
                <div class="py-4">
                    <h4 class="text-gray-800 text-base font-extrabold">{{ user.username }}</h4>
                    <p class="text-gray-800 text-xs mt-1">Food Enthusiast</p>
                    <div class="flex justify-center my-6">
                        <button type="button" id="openModalBtn" class="bg-blue-web text-white font-bold py-2 px-4 rounded-lg">
                            Add Journal Entry
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="overflow-x-auto">
        <div class="flex flex-col items-center justify-center min-h-[24rem] p-6 w-full">
            <div id="exist_entry_cards"></div>
            <div id="journal_entry_cards" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 w-full max-w-6xl mx-auto">
            </div>
            <!-- Modal Structure -->
            <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
                <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
                    <!-- Modal header -->
                    <div class="flex items-center justify-between p-4 border-b rounded-t">
                        <h3 class="text-xl font-semibold text-gray-900">Add New Entry</h3>
                        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                    </div>

                    <!-- Modal body -->
                    <div class="px-6 py-4 space-y-6 form-style">
                        <form id="journalEntryForm">
                            <div class="mb-4">
                                <label for="name" class="block text-sm font-medium text-gray-700">Title</label>
                                <input type="text" id="title" name="title" class="mt-1 block w-full border border-gray-300 rounded-md p-2" required>
                            </div>
                            <div class="mb-4">
                                <label for="store" class="block text-sm font-medium text-gray-700">Store</label>
                                <select id="store" name="store" class="mt-1 block w-full border border-gray-300 rounded-md p-2" required>
                                    <option value="">Select a Store</option>
                                </select>
                            </div>
                            <div class="mb-4">
                                <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                                <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2" placeholder="Tell us about your experience..." required></textarea>
                            </div>
                            <div class="mb-4">
                                <label for="ratings" class="block text-sm font-medium text-gray-700">Ratings</label>
                                <input type="number" id="ratings" name="ratings" min="0" max="5" class="mt-1 block w-full border border-gray-300 rounded-md p-2 " required>
                            </div>
                        </form>
                    </div>

                    <!-- Modal footer -->
                    <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
                        <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
                        <button type="submit" id="submitJournalEntry" form="journalEntryForm" class="bg-blue-web hover:bg-blue-web text-white font-bold py-2 px-4 rounded-lg">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    document.addEventListener("DOMContentLoaded", function () {
    // Fetch and display existing journal entries on page load
        refreshJournalEntries();  // Add this line to fetch existing entries on page load
        
        // Button to open modal
        document.getElementById("openModalBtn").addEventListener("click", function() {
            populateStoreDropdown();  // Populate dropdown when modal opens
            showModal();  // Show modal
        });

        // Modal close buttons
        document.getElementById("cancelButton").addEventListener("click", hideModal);
        document.getElementById("closeModalBtn").addEventListener("click", hideModal);

        // Form submission handler
        document.getElementById("journalEntryForm").addEventListener("submit", function (e) {
            e.preventDefault(); // Prevent default form submission
            addJournalEntry();   // Custom function to handle journal entry submission
        });
    });


    // Function to populate the store dropdown via AJAX
    function populateStoreDropdown() {
        fetch("{% url 'dashboard:get_stores' %}")
            .then(response => response.json())
            .then(stores => {
                const storeSelect = document.getElementById("store");
                storeSelect.innerHTML = '<option value="">Select a Store</option>'; // Clear existing options

                stores.forEach(store => {
                    const option = document.createElement("option");
                    option.value = store.name;
                    option.textContent = store.name;  // Add store names as options
                    storeSelect.appendChild(option);
                });
            })
            .catch(error => console.error('Error fetching stores:', error));  // Error handling
    }

    // Function to show the modal
    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden');
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); // Smooth transition
    }

    // Function to hide the modal
    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150); // Smooth transition
    }

    // Function to handle journal entry submission via AJAX
    function addJournalEntry() {
        fetch("{% url 'dashboard:create_journal_entry_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#journalEntryForm')),  // Serialize form data
        })
        .then(response => {
            refreshJournalEntries();  // Refresh journal entries after successful form submission
        })
        .catch(error => console.error('Error submitting journal entry:', error)); // Error handling

        document.getElementById("journalEntryForm").reset();  // Reset form
        hideModal();  // Hide modal after submission
    }

    async function getJournalEntries() {
        return fetch("{% url 'dashboard:show_json' %}")
            .then(response => {
                if (!response.ok) {
                    throw new Error("Failed to fetch journal entries.");
                }
                return response.json();
            })
            .catch(error => console.error('Error fetching journal entries:', error));
    }

    // Function to refresh journal entries
    async function refreshJournalEntries() {
        const journalEntryCards = document.getElementById("journal_entry_cards");
        const missingEntryCards = document.getElementById("exist_entry_cards");
        missingEntryCards.innerHTML = ""; // Clear current entries
        journalEntryCards.innerHTML = ""; // Clear current entries

        try {
            const journalEntries = await getJournalEntries(); // Fetch journal entries via AJAX
            console.log(journalEntries); // Add this line to see the data

            if (journalEntries.length === 0) {
                missingEntryCards.innerHTML = `
                    <div class="flex flex-col items-center justify-center min-h-[24rem] w-full text-center">
                        <img src="https://www.svgrepo.com/show/525569/upload-minimalistic.svg" alt="No Journal Entry Added" class="w-32 h-32 mb-4" />
                        <p class="text-gray-600 mt-4">Please, add at least one Entry.</p>
                    </div>
                `;
            } else {
                journalEntries.forEach((item) => {
                    const user = DOMPurify.sanitize(item.fields.user);
                    const title = DOMPurify.sanitize(item.fields.title);
                    const store = DOMPurify.sanitize(item.fields.store);
                    const description = DOMPurify.sanitize(item.fields.description);
                    const ratings = DOMPurify.sanitize(item.fields.ratings);
                    const time = DOMPurify.sanitize(item.fields.time);

                    journalEntryCards.innerHTML += 
                        `
                        <div>
                            <div class="bg-white cursor-pointer rounded overflow-hidden shadow-[0_2px_10px_-3px_rgba(6,81,237,0.3)] relative top-0 hover:-top-2 transition-all duration-300">
                                <div class="p-6">
                                    <span class="text-sm block text-gray-400 mb-2">Created ${time}</span>
                                    <h3 class="text-xl font-bold text-gray-800">${title}</h3>
                                    <span class="text-xs text-white bg-blue-500 rounded-full px-3 py-1">${ratings} Stars</span>
                                    <hr class="my-4" />
                                    <p class="text-gray-400 text-sm">${description}</p>
                                </div>
                                <div class="flex space-x-2 justify-center my-4">
                                    <a href="/edit-journal/${item.pk}" class=" bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                                    Edit
                                    </a>
                                    <a href="/delete-journal/${item.pk}" class=" bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                                    Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    `;
                });
            }
        } catch (error) {
            console.error('Error refreshing journal entries:', error);
        }
    }
</script>

{% endblock content %}