dashboard/urls.py
from django.urls import path
from .views import show_main, register, login_user, logout_user, profile, show_xml_by_id, show_json, show_json_by_id, show_xml, edit_journal, delete_journal, create_journal_entry_ajax, get_stores

app_name = 'dashboard'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),\
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('edit-journal/<uuid:id>', edit_journal, name='edit_journal'),
    path('delete-journal/<uuid:id>', delete_journal, name='delete_journal'),
    path('create_journal_entry_ajax', create_journal_entry_ajax, name='create_journal_entry_ajax'),
    path('get-stores/', get_stores, name='get_stores'),
]

dashboard_admin/urls.py
from django.urls import path
from .views import show_main, create_toko_entry, create_product_entry, show_xml, show_json, edit_toko, edit_product, delete_toko, delete_product, show_xml_toko_by_id, show_xml_produk_by_id, show_json_toko_by_id, show_json_produk_by_id
from .views import all_toko_json, all_product_json, products_for_toko_json, create_product_flutter, create_restaurant_flutter, get_products_by_toko
from .views import delete_toko_flutter, update_toko_flutter, delete_product_flutter, update_product_flutter, get_all_toko_names
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard_admin'

urlpatterns = [
    # Halaman utama dan manajemen toko/produk
    path('', show_main, name='show_main'),
    path('create-toko/', create_toko_entry, name='create_toko_entry'),
    path('create-product/', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name="show_json"),
    path('xml/toko/<str:id>/', show_xml_toko_by_id, name="show_xml_toko_by_id"),
    path('xml/produk/<str:id>/', show_xml_produk_by_id, name="show_xml_produk_by_id"),
    path('json/toko/<str:id>/', show_json_toko_by_id, name="show_json_toko_by_id"),
    path('json/produk/<str:id>/', show_json_produk_by_id, name="show_json_produk_by_id"),
    path('edit-toko/<uuid:id>', edit_toko, name="edit_toko"),
    path('edit-product/<uuid:id>', edit_product, name="edit_product"),
    path('delete-toko/<uuid:id>/', delete_toko, name="delete_toko"),
    path('delete-product/<uuid:id>', delete_product, name="delete_product"),
    
    # Route untuk mendapatkan semua data toko dan produk dalam format JSON
    path('all-toko/', all_toko_json, name='all_toko_json'),
    path('all-product/', all_product_json, name='all_product_json'),

    # Menambahkan route untuk mengambil produk berdasarkan toko yang dipilih
    # Menggunakan produk_for_toko_json yang sudah didefinisikan di views.py
    path('json/products-for-toko/<uuid:toko_id>/', products_for_toko_json, name='products_for_toko_json'),
    path('create-product-flutter/', create_product_flutter, name='create_product_flutter'),
    path('create-restaurant-flutter/', create_restaurant_flutter, name='create_restaurant_flutter'),
    path('get-products-by-toko/<uuid:toko_id>/', get_products_by_toko, name='get_products_by_toko'),
    path('delete-toko-flutter/<uuid:id>/', delete_toko_flutter, name='delete_toko_flutter'),
    path('update-toko-flutter/<uuid:id>/', update_toko_flutter, name='update_toko_flutter'),
    path('delete-product-flutter/<uuid:id>/', delete_product_flutter, name='delete_product_flutter'),
    path('update-product-flutter/<uuid:id>/', update_product_flutter, name='update_product_flutter'),
    path('get-all-toko-names/', get_all_toko_names, name='get_all_toko_names')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

why_bandung/urls.py
from django.contrib import admin
from django.urls import path, include, include
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admintab/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product_page.urls')),
    path('admin/', include('dashboard_admin.urls')),
    path('whatToEat/', include('whatToEat.urls')),
    path('geomap/', include('geomapping.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard_admin/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
import uuid

# Create your models here.
class TokoEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, unique=True)
    location = models.TextField()

    def __str__(self):
        return self.name
    
    def to_json(self):
        return {
            'id': str(self.id),
            'name': self.name,
            'location': self.location
        }

class ProductEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField(validators=[MinValueValidator(1)])
    description = models.TextField()
    image = models.URLField(max_length=500, blank=True, null=True)
    toko = models.ForeignKey(TokoEntry, on_delete=models.CASCADE, related_name='products')

    def to_json(self):
        return {
            'id': str(self.id),
            'name': self.name,
            'price': self.price,
            'description': self.description,
            'image': self.image,
            'toko_id': str(self.toko.id),
            'toko_name': self.toko.name
        }

dashboard_admin/forms.py
from django.forms import ModelForm
from dashboard_admin.models import TokoEntry, ProductEntry
from django import forms

class TokoEntryForm(ModelForm):
    class Meta:
        model = TokoEntry
        fields = ['name', "location"]

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if TokoEntry.objects.filter(name=name).exists():
            raise forms.ValidationError("Nama toko sudah digunakan, silahkan gunakan nama lain")
        return name

class ProductEntryForm(ModelForm):
    class Meta:
        model = ProductEntry

        fields = ["name", "price", "description", "image", "toko"]

    def clean(self):
        cleaned_data = super().clean()
        toko = TokoEntry.objects.all()

        # Cek apakah ada toko yang sudah terdaftar
        if not TokoEntry.objects.exists():
            raise forms.ValidationError("Tidak ada toko yang tersedia. Anda harus menambahkan toko sebelum menambahkan produk.")
        
        return cleaned_data

dashboard_admin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TokoEntryForm, ProductEntryForm
from .models import TokoEntry, ProductEntry
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from django.core.exceptions import ValidationError
import re
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from rest_framework import viewsets
from .serializer import TokoEntrySerializer, ProductEntrySerializer
from rest_framework.decorators import action, api_view
from rest_framework.response import Response
from rest_framework.views import APIView

def show_main(request):
    toko_entries = TokoEntry.objects.all()
    product_entries = ProductEntry.objects.all()

    unique_locations = set(toko_entry.location.lower() for toko_entry in toko_entries)
    unique_locations_display = {location: toko_entry.location for toko_entry in toko_entries for location in unique_locations if location == toko_entry.location.lower()}

    
    context = {
        'toko_entries': toko_entries,
        'product_entries': product_entries,
        'unique_locations': unique_locations_display.values(),
    }

    return render(request, "boardadmin.html", context)

def create_toko_entry(request):
    form = TokoEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect ('dashboard_admin:show_main')
    
    context = {'form': form}
    return render(request, "create_toko_entry.html", context)

def create_product_entry(request):
    if request.method == "POST":
        form = ProductEntryForm(request.POST, request.FILES)  
        if form.is_valid():
            try:
                form.save()
                return redirect('dashboard_admin:show_main')
            except ValidationError as e:
                form.add_error('name', e)
    else:
        form = ProductEntryForm()

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    toko_data = serializers.serialize("xml", TokoEntry.objects.all())
    product_data = serializers.serialize("xml", ProductEntry.objects.all())

    # Menghapus deklarasi XML <?xml ... ?> dari kedua hasil serialisasi
    toko_data = re.sub(r'<\?xml[^>]+\?>', '', toko_data)
    product_data = re.sub(r'<\?xml[^>]+\?>', '', product_data)

    # Gabungkan keduanya dalam satu XML dengan root <data>
    xml_data = f'<?xml version="1.0" encoding="UTF-8"?>\n<data>\n<toko>{toko_data}</toko>\n<produk>{product_data}</produk>\n</data>'

    # Return hasil XML gabungan
    return HttpResponse(xml_data, content_type="application/xml")

def show_xml_toko_by_id(request, id):
    try:
        # Ambil data toko berdasarkan id
        toko = get_object_or_404(TokoEntry, pk=id)

        # Serialize data dari model TokoEntry berdasarkan id
        toko_data = serializers.serialize("xml", [toko])  # serialize toko sebagai list

        # Menghapus deklarasi XML <?xml ... ?> dari hasil serialisasi
        toko_data = re.sub(r'<\?xml[^>]+\?>', '', toko_data)

        # Return hasil XML dari toko saja
        xml_data = f'<?xml version="1.0" encoding="UTF-8"?>\n<toko>{toko_data}</toko>'
        return HttpResponse(xml_data, content_type="application/xml")

    except TokoEntry.DoesNotExist:
        return HttpResponse("<error>Toko with given ID does not exist.</error>", content_type="application/xml", status=404)

def show_xml_produk_by_id(request, id):
    try:
        # Ambil toko berdasarkan id
        product = get_object_or_404(ProductEntry, pk=id)

        # Serialize data dari model ProductEntry berdasarkan toko yang diambil
        product_data = serializers.serialize("xml", [product])

        # Menghapus deklarasi XML <?xml ... ?> dari hasil serialisasi
        product_data = re.sub(r'<\?xml[^>]+\?>', '', product_data)

        # Return hasil XML dari produk saja
        xml_data = f'<?xml version="1.0" encoding="UTF-8"?>\n<produk>{product_data}</produk>'
        return HttpResponse(xml_data, content_type="application/xml")

    except TokoEntry.DoesNotExist:
        return HttpResponse("<error>Toko with given ID does not exist.</error>", content_type="application/xml", status=404)

def show_json(request):
    # Serialize data dari model TokoEntry dan ProductEntry
    toko_data = serializers.serialize("json", TokoEntry.objects.all())
    product_data = serializers.serialize("json", ProductEntry.objects.all())

    # Mengubah string JSON menjadi list of dict agar bisa digabungkan
    toko_data = json.loads(toko_data)
    product_data = json.loads(product_data)

    # Gabungkan data menjadi satu dict dengan dua kunci: 'toko' dan 'produk'
    combined_data = {
        "toko": toko_data,
        "produk": product_data
    }

    # Return JSON response
    return JsonResponse(combined_data)

def all_toko_json(request):
    toko_list = TokoEntry.objects.all()
    data = [toko.to_json() for toko in toko_list]
    return JsonResponse({'toko': data})

def all_product_json(request):
    product_list = ProductEntry.objects.all()
    data = [product.to_json() for product in product_list]
    return JsonResponse({'products': data})

def show_json_toko_by_id(request, id):
    try:
        # Ambil data toko berdasarkan id
        toko = get_object_or_404(TokoEntry, pk=id)

        # Serialize data dari model TokoEntry berdasarkan id
        toko_data = serializers.serialize("json", [toko])  # serialize toko sebagai list

        # Mengubah string JSON menjadi list of dict agar lebih fleksibel
        toko_data = json.loads(toko_data)

        # Return hasil JSON dari toko saja
        return JsonResponse({"toko": toko_data}, safe=False)

    except TokoEntry.DoesNotExist:
        return JsonResponse({"error": "Toko with given ID does not exist."}, status=404)

def show_json_produk_by_id(request, id):
    try:
        # Ambil toko berdasarkan id
        product = get_object_or_404(ProductEntry, pk=id)

        # Serialize data dari model ProductEntry berdasarkan toko yang diambil
        product_data = serializers.serialize("json", [product])

        # Mengubah string JSON menjadi list of dict agar lebih fleksibel
        product_data = json.loads(product_data)

        # Return hasil JSON dari produk saja
        return JsonResponse({"produk": product_data}, safe=False)

    except TokoEntry.DoesNotExist:
        return JsonResponse({"error": "Toko with given ID does not exist."}, status=404)

def edit_toko(request, id):
    # Ambil data toko berdasarkan id
    toko = get_object_or_404(TokoEntry, pk=id)

    # Set TokoEntry sebagai instance dari form
    form = TokoEntryForm(request.POST or None, instance=toko)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman utama
        form.save()
        return HttpResponseRedirect(reverse('dashboard_admin:show_main'))

    context = {'form': form}
    return render(request, "edit_toko.html", context)

def edit_product(request, id):
    # Ambil data produk berdasarkan id
    product = get_object_or_404(ProductEntry, pk=id)

    # Set ProductEntry sebagai instance dari form
    form = ProductEntryForm(request.POST or None, request.FILES or None, instance=product)


    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman utama
        form.save()
        return HttpResponseRedirect(reverse('dashboard_admin:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_toko(request, id):
    toko = get_object_or_404(TokoEntry, pk=id)
    toko.delete()
    return HttpResponseRedirect(reverse('dashboard_admin:show_main'))

def delete_product(request, id):
    product = get_object_or_404(ProductEntry, pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('dashboard_admin:show_main'))

class TokoEntryViewSet(viewsets.ModelViewSet):
    queryset = TokoEntry.objects.all()
    serializer_class = TokoEntrySerializer

class ProductEntryViewSet(viewsets.ModelViewSet):
    queryset = ProductEntry.objects.all()
    serializer_class = ProductEntrySerializer

    @action(detail=True, methods=['get'])
    def products_for_toko(self, request, pk=None):
        toko = self.get_object()
        products = toko.products.all()
        serializer = ProductEntrySerializer(products, many=True)
        return Response(serializer.data)
    
class ProductsForTokoView(APIView):
    def get(self, request, toko_id, format=None):
        products = ProductEntry.objects.filter(toko__id=toko_id)
        serializer = ProductEntrySerializer(products, many=True)
        return Response(serializer.data)
    
@api_view(['GET'])
def products_for_toko_json(request, toko_id):
    try:
        # Mengambil semua produk berdasarkan toko_id
        products = ProductEntry.objects.filter(toko_id=toko_id)
        serializer = ProductEntrySerializer(products, many=True)
        return Response(serializer.data)
    except ProductEntry.DoesNotExist:
        return Response({'error': 'Products not found for this store'}, status=404)
    
@api_view(['POST'])
def create_product_flutter(request):
    if request.method == 'POST':
        data = request.data
        try:
            product = ProductEntry.objects.create(
                name=data['name'],
                price=data['price'],
                description=data['description'],
                image=data['image'],
                toko_id=data['toko'],
            )
            product.save()
            return Response({'status': 'success', 'message': 'Product added successfully!'}, status=201)
        except Exception as e:
            return Response({'status': 'error', 'message': str(e)}, status=400)
        
@api_view(['POST'])
def create_restaurant_flutter(request):
    if request.method == 'POST':
        data = request.data
        try:

dashboard_admin/templates/boardadmin.html
{% extends 'base.html' %}
{% block content %}

{% if not toko_entries %}
<div class="m-6"><br><br></div>
<div class="flex flex-col justify-center items-center min-h-screen mt-8">
  <a href="{% url 'dashboard_admin:create_toko_entry' %}">
    <button class="btn-add mb-4">Add New Restaurant</button>
  </a>
  <p class="text-gray-600">Belum ada Toko dan Produk di database.</p>
</div>

<!-- Jika sudah ada toko di database -->
{% else %}
<div class="flex flex-col justify-center items-center mt-8 gap-4">
  <div class="button-container flex gap-4">
    <a href="{% url 'dashboard_admin:create_toko_entry' %}">
      <button class="btn-add">Add New Restaurant</button>
    </a>
    <a href="{% url 'dashboard_admin:create_product_entry' %}">
      <button class="btn-add">Add New Product</button>
    </a>
  </div>

  <div class="filter-container flex justify-center gap-4">
    <label class="inline-flex items-center cursor-pointer">
      <input type="checkbox" id="toggleDropdown" class="sr-only peer">
      <div class="relative w-11 h-6 bg-blue-web peer-focus:outline-none peer-focus:ring-4 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-web"></div>
      <span class="ms-3 text-sm font-medium text-gray-900 dark:text-gray-600">Filter by Location</span>
    </label>
  </div>

  <div class="flex flex-col justify-center items-center mt-4 gap-4">
    <!-- Dropdown Filter Lokasi dengan multiple selection (tersembunyi pada awalnya) -->
    <select id="locationFilter" class="bg-gray-200 p-2 rounded-lg hidden mt-4" multiple size="4">
      {% for location in unique_locations %}
        <option value="{{ location }}">{{ location }}</option>
      {% endfor %}
    </select>

    <!-- Tombol untuk menghapus semua pilihan di dropdown -->
    <button id="clearSelection" class="btn-add bg-red-500 hover:bg-red-600 hidden">
      Clear Location Filter Selection
    </button>
  </div>



</div>


<!-- Tampilkan daftar toko dan produk jika ada toko di database -->
<div class="card-container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 justify-start p-4">
  {% for toko_entry in toko_entries %}
  <div class="bg-white shadow-md rounded-lg overflow-hidden toko-card" data-location="{{ toko_entry.location }}">
    <div class="p-5 border-b">
      <h3 class="font-bold text-xl mb-2">{{ toko_entry.name }}</h3>
      <p class="text-gray-600">Lokasi: {{ toko_entry.location }}</p>

      <!-- Edit and Delete Restaurant -->
      <div class="flex justify-end space-x-2 mt-4">
        <a href="{% url 'dashboard_admin:edit_toko' id=toko_entry.id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="currentColor" class="h-6 w-6">
            <path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152L0 424c0 48.6 39.4 88 88 88l272 0c48.6 0 88-39.4 88-88l0-112c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 112c0 22.1-17.9 40-40 40L88 464c-22.1 0-40-17.9-40-40l0-272c0-22.1 17.9-40 40-40l112 0c13.3 0 24-10.7 24-24s-10.7-24-24-24L88 64z"/>
            </svg>
        </a>
        <a href="{% url 'dashboard_admin:delete_toko' id=toko_entry.id %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor" class="h-6 w-6">
            <path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/>
            </svg>
        </a>
      </div>
    </div>
    
    <!-- Product list -->
    <div class="p-5">
      <p class="font-semibold text-lg mb-2">Daftar Produk:</p>

      {% if toko_entry.products.exists %}
      <div class="product-list space-y-4">
        {% for product_entry in toko_entry.products.all %}
        <div class="product-item border-t pt-2 flex items-center justify-between">
          <div class="flex-1">
            <h4 class="text-lg font-semibold">{{ product_entry.name }}</h4>
            <p class="text-gray-700">{{ product_entry.description }}</p>
            <br>
            <span class="border-t border-b bg-yellow-200 text-gray-600 px-3 py-1 rounded-full">Rp {{ product_entry.price }}</span>
            <div class="flex gap-4 mt-2">
              <a href="{% url 'dashboard_admin:edit_product' id=product_entry.id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="currentColor" class="h-6 w-6">
                  <path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152L0 424c0 48.6 39.4 88 88 88l272 0c48.6 0 88-39.4 88-88l0-112c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 112c0 22.1-17.9 40-40 40L88 464c-22.1 0-40-17.9-40-40l0-272c0-22.1 17.9-40 40-40l112 0c13.3 0 24-10.7 24-24s-10.7-24-24-24L88 64z"/>
                  </svg>
              </a>
              <a href="{% url 'dashboard_admin:delete_product' id=product_entry.id %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor" class="h-6 w-6">
                  <path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                  </svg>
              </a>
            </div>
          </div>
          {% if product_entry.image %}
          <img src="{{ product_entry.image }}" alt="{{ product_entry.name }}" class="w-32 h-32 object-cover ml-4 rounded-md">
          {% else %}
          <p class="text-gray-500">No Image</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      {% else %}
      <p class="text-gray-500">Belum ada produk dalam toko ini.</p>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}

<br />

<script>
  // Fungsi untuk memunculkan atau menyembunyikan dropdown filter lokasi
  document.getElementById('toggleDropdown').addEventListener('click', function() {
    var dropdown = document.getElementById('locationFilter');
    dropdown.classList.toggle('hidden');
    
    var clearBtn = document.getElementById('clearSelection');
    clearBtn.classList.toggle('hidden');
  });

  // Fungsi untuk memfilter toko berdasarkan lokasi yang dipilih
  function filterTokoByLocation() {
    var selectedLocations = [];
    var selectElement = document.getElementById('locationFilter');
    var selectedOptions = Array.from(selectElement.selectedOptions);

    selectedOptions.forEach(function(option) {
      selectedLocations.push(option.value.toLowerCase());
    });

    var tokoCards = document.querySelectorAll('.toko-card');

    tokoCards.forEach(function(card) {
      var location = card.getAttribute('data-location').toLowerCase();

      if (selectedLocations.length === 0 || selectedLocations.includes(location)) {
        card.style.display = "block";  // Tampilkan kartu jika cocok dengan filter
      } else {
        card.style.display = "none";  // Sembunyikan kartu jika tidak cocok
      }
    });
  }

  // Event listener untuk dropdown filter
  document.getElementById('locationFilter').addEventListener('change', filterTokoByLocation);

  // Fungsi untuk menghapus pilihan di dropdown (Clear Selection)
  document.getElementById('clearSelection').addEventListener('click', function() {
    var selectElement = document.getElementById('locationFilter');
    selectElement.selectedIndex = -1;  // Deselect semua opsi

    filterTokoByLocation();  // Reset filter untuk menampilkan semua toko
  });
</script>

{% endblock content %}